# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rite < Formula
  desc "Task runner with Unix-native variable precedence (hard fork of go-task)."
  homepage "https://github.com/clintmod/rite"
  version "1.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/clintmod/rite/releases/download/v1.0.9/rite_darwin_amd64.tar.gz"
      sha256 "1b1caf8839afcf580d3a3b076d92db95eb5c9eb8bd4540fcc3e4d8644b9728b5"

      define_method(:install) do
        bin.install "rite"
        bash_completion.install "internal/task/completion/bash/task.bash" => "rite"
        zsh_completion.install "internal/task/completion/zsh/_task" => "_rite"
        fish_completion.install "internal/task/completion/fish/task.fish" => "rite.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/clintmod/rite/releases/download/v1.0.9/rite_darwin_arm64.tar.gz"
      sha256 "ee744a4e9eb9a3ca6b735fa10902575c580d2aeb81642114d3e044c1327fbfaa"

      define_method(:install) do
        bin.install "rite"
        bash_completion.install "internal/task/completion/bash/task.bash" => "rite"
        zsh_completion.install "internal/task/completion/zsh/_task" => "_rite"
        fish_completion.install "internal/task/completion/fish/task.fish" => "rite.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/clintmod/rite/releases/download/v1.0.9/rite_linux_amd64.tar.gz"
      sha256 "516637c46f506282199d9994f2060da2116e0017d0b477025b5163ba279da029"
      define_method(:install) do
        bin.install "rite"
        bash_completion.install "internal/task/completion/bash/task.bash" => "rite"
        zsh_completion.install "internal/task/completion/zsh/_task" => "_rite"
        fish_completion.install "internal/task/completion/fish/task.fish" => "rite.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/clintmod/rite/releases/download/v1.0.9/rite_linux_arm.tar.gz"
      sha256 "60e28fc77c1412bb8142d63012320da399c8ffbb381ed24af2dcc75c0840051c"
      define_method(:install) do
        bin.install "rite"
        bash_completion.install "internal/task/completion/bash/task.bash" => "rite"
        zsh_completion.install "internal/task/completion/zsh/_task" => "_rite"
        fish_completion.install "internal/task/completion/fish/task.fish" => "rite.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clintmod/rite/releases/download/v1.0.9/rite_linux_arm64.tar.gz"
      sha256 "590089facbdd853dc43b701395e341baafe955659a38e4b207080a600a869a27"
      define_method(:install) do
        bin.install "rite"
        bash_completion.install "internal/task/completion/bash/task.bash" => "rite"
        zsh_completion.install "internal/task/completion/zsh/_task" => "_rite"
        fish_completion.install "internal/task/completion/fish/task.fish" => "rite.fish"
      end
    end
  end

  test do
    system "#{bin}/rite", "--help"
  end
end
