# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rite < Formula
  desc "Task runner with Unix-native variable precedence (hard fork of go-task)."
  homepage "https://github.com/clintmod/rite"
  version "1.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/clintmod/rite/releases/download/v1.0.6/rite_darwin_amd64.tar.gz"
      sha256 "4b6d6e1b58809aed3b6f5533351cbecbc6e05db1fe6f2588ec61fd7368ece39f"

      define_method(:install) do
        bin.install "rite"
        bash_completion.install "internal/task/completion/bash/task.bash" => "rite"
        zsh_completion.install "internal/task/completion/zsh/_task" => "_rite"
        fish_completion.install "internal/task/completion/fish/task.fish" => "rite.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/clintmod/rite/releases/download/v1.0.6/rite_darwin_arm64.tar.gz"
      sha256 "fe8fabe6916a98fd548e64841ff6f6d8601fc26aff5927fed22ebe24019a4c70"

      define_method(:install) do
        bin.install "rite"
        bash_completion.install "internal/task/completion/bash/task.bash" => "rite"
        zsh_completion.install "internal/task/completion/zsh/_task" => "_rite"
        fish_completion.install "internal/task/completion/fish/task.fish" => "rite.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/clintmod/rite/releases/download/v1.0.6/rite_linux_amd64.tar.gz"
      sha256 "f5aac8588a70ff0b6ba6df58fe5d54bda14b21444e7e3868377f34dcb74db8b4"
      define_method(:install) do
        bin.install "rite"
        bash_completion.install "internal/task/completion/bash/task.bash" => "rite"
        zsh_completion.install "internal/task/completion/zsh/_task" => "_rite"
        fish_completion.install "internal/task/completion/fish/task.fish" => "rite.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/clintmod/rite/releases/download/v1.0.6/rite_linux_arm.tar.gz"
      sha256 "e2aa96b057ba8fd9c95f0318046c6cbc5d888a8928c061ff69a9a6b2468ca543"
      define_method(:install) do
        bin.install "rite"
        bash_completion.install "internal/task/completion/bash/task.bash" => "rite"
        zsh_completion.install "internal/task/completion/zsh/_task" => "_rite"
        fish_completion.install "internal/task/completion/fish/task.fish" => "rite.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clintmod/rite/releases/download/v1.0.6/rite_linux_arm64.tar.gz"
      sha256 "352f8ff40fd0673f5cb1e50c080da082e2395e88be5a1d2f58e8ec0d1f68c14c"
      define_method(:install) do
        bin.install "rite"
        bash_completion.install "internal/task/completion/bash/task.bash" => "rite"
        zsh_completion.install "internal/task/completion/zsh/_task" => "_rite"
        fish_completion.install "internal/task/completion/fish/task.fish" => "rite.fish"
      end
    end
  end

  test do
    system "#{bin}/rite", "--help"
  end
end
